version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flights_db
    ports:
      - "5434:5432"  # הפורט החיצוני 5434, הפנימי   נשאר 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: .
    ports:
      - "5000:5000"  # הגדרת הפורט 5000 עבור השרת
    depends_on:
      - db

volumes:
  db_data:
