name: CI/CD Pipeline  # שם הצינור

# מתי להריץ את התהליך (בכל `push` או `pull_request` ל-master)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:  # שלב הבנייה
    runs-on: ubuntu-latest  # מריץ את השלבים על שרת Ubuntu

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # שליפת הקוד מ-GitHub

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  
      # הגדרת Docker לבנייה

    - name: Log in to Docker Hub
      uses: docker/login-action@v1  # כניסה ל-Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flight-booking:latest
